server:
  port: 8092

pgsql:
  datasource:
    url: jdbc:postgresql://39.107.127.218:5432/study
    name: study
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver